##################
# All rules specific to this repo
##################

inherit_from: .rubocop_general.yml

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
